name: dusty_dust
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
isar_version: &isar_version 3.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  isar: *isar_version
  isar_flutter_libs: *isar_version
  path_provider: ^2.1.5
  get_it: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  isar_generator: *isar_version
#  build_runner: ^2.7.2
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - asset/img/
    - .env
  fonts:
    - family: sunFlower
      fonts:
        - asset: asset/fonts/Sunflower-Bold.ttf
          weight: 700
        - asset: asset/fonts/Sunflower-Medium.ttf
          weight: 500
        - asset: asset/fonts/Sunflower-Light.ttf
          weight: 300